workflows:
  android-debug:
    name: Android Debug APK
    instance_type: mac_mini_m2

    environment:
      node: 22

    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - cd android
      - ls -la
      - ls -la gradle/wrapper || true
      - ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk